require: rubocop-rails

Style/FrozenStringLiteralComment:
        Enabled: false

Style/StringLiterals:
        Enabled: false

Style/Documentation:
        Enabled: false

Rails/FilePath:
        Enabled: false
